'use client';
import Link from 'next/link'; import { motion } from 'framer-motion'; import { ArrowRight, GithubLogo, Moon, Sun } from '@phosphor-icons/react'; import { useEffect, useState } from 'react';
const domains=[['Technology','Machine Learning · Backend · DevOps'],['Science','Physics · Biology'],['Mathematics','Linear Algebra · Statistics'],['Business','Marketing · Accounting'],['Creative','Photography · UI/UX'],['Languages','English · Spanish · French']];
export default function Home(){const [dark,setDark]=useState(true);useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light'},[dark]);return <main><nav><Link className="brand" href="/"><span className="mark">O</span>OpenRoadmap<span className="dot">.</span></Link><div className="navlinks"><Link href="/roadmaps">Roadmaps</Link><Link href="/docs">Docs</Link><a href="#how">How it works</a></div><div className="navright"><button className="iconbtn" onClick={()=>setDark(!dark)} aria-label="Toggle theme">{dark?<Sun size={19}/>:<Moon size={19}/>}</button><a className="github" href="https://github.com" target="_blank" rel="noreferrer"><GithubLogo size={18}/> GitHub</a></div></nav><section className="hero"><div className="gridbg"/><span className="eyebrow">OPEN STANDARD · COMMUNITY DIRECTORY</span><motion.h1 initial={{opacity:0,y:20}} animate={{opacity:1,y:0}}>Know what to learn.<br/><span>Know where to look.</span></motion.h1><p>The open standard and community directory for structured learning roadmaps. Discover human-curated, AI-generated, and hybrid paths using the best resources already available across the internet.</p><div className="heroactions"><Link className="primary" href="/roadmaps">Explore roadmaps <ArrowRight/></Link><Link className="secondary" href="/docs">View documentation</Link></div><div className="searchsim"><small>WHAT DO YOU WANT TO LEARN?</small><div>machine learning<span className="cursor">_</span></div><p>⌕ Searching OpenRoadmap...</p><Link href="/roadmaps/machine-learning-engineer">Machine Learning Engineer <ArrowRight/></Link><Link href="/roadmaps/backend-developer">Backend Engineering <ArrowRight/></Link></div></section><section className="manifest"><div className="manifestbig">RESOURCES ARE EVERYWHERE.<br/><span>THE PATH BETWEEN THEM ISN&apos;T.</span></div><p>OpenRoadmap organizes topics, order, recommended resources, and alternatives without hosting course content.</p></section><section className="section" id="how"><span className="kicker">HOW IT WORKS</span><h2>From scattered tabs<br/>to a structured path.</h2><div className="flow">{['Find a roadmap','See what to learn','Understand the order','Choose where to learn'].map((x,i)=><div className="flowstep" key={x}><b>0{i+1}</b><h3>{x}</h3><span>{i<3?'↓':'↗'}</span></div>)}</div></section><section className="section"><span className="kicker">ANYTHING LEARNABLE</span><h2>One format.<br/><em>Any subject.</em></h2><div className="domain-grid">{domains.map(([a,b])=><div className="domain" key={a}><b>{a}</b><p>{b}</p></div>)}</div></section><section className="section standard"><div><span className="kicker">THE OPEN STANDARD</span><h2>Any author.<br/>Any model.</h2><p>Human, AI, and hybrid roadmaps share one provider-independent YAML format. Bring any model—or none at all.</p></div><pre>{`spec: openroadmap/v0.1
subject: photography
authorship:
  type: human
sections:
  - title: Composition
    topics: []`}</pre></section><section className="section contribution"><span className="kicker">OPEN SOURCE</span><h2>The directory<br/><em>is the community.</em></h2><div className="flow">{['Fork','Create or improve','Validate','Pull Request','Community Review','Merge'].map((x,i)=><div className="flowstep" key={x}><b>{String(i+1).padStart(2,'0')}</b><h3>{x}</h3></div>)}</div><Link className="primary" href="/docs/create-roadmap">Create a roadmap <ArrowRight/></Link></section><footer><div className="brand"><span className="mark">O</span>OpenRoadmap<span className="dot">.</span></div><p>Know what to learn. Know where to look.</p><div><Link href="/roadmaps">Roadmaps</Link> · <Link href="/docs">Documentation</Link> · <Link href="/docs/ai-authoring">AI authoring</Link></div></footer></main>}
