'use client';
import Link from 'next/link'; import Breadcrumbs from '../../components/breadcrumbs'; import { useState } from 'react';
const prompt=`Read AGENTS.md, docs/SPEC.md, docs/AI_AUTHORING.md and the OpenRoadmap schema.

Create a high-quality OpenRoadmap for:

<SUBJECT>

Follow the current specification. Use reputable resources, do not fabricate URLs, declare authorship and AI provenance accurately, run npm run validate, and fix every validation error before finishing.`;
const publicSteps=['Fork','Create branch','Add roadmap','Validate','Open PR','Review','Merge']; const repoSteps=['Create branch','Make changes','Validate','Open PR','Review','Merge'];
export default function Guide(){const [copied,setCopied]=useState(false);const copy=()=>{navigator.clipboard?.writeText(prompt);setCopied(true);setTimeout(()=>setCopied(false),1600)};return <main className="directory doc guide-page"><Breadcrumbs items={[{label:'Guide'}]} /><section className="guide-hero"><span className="kicker">CONTRIBUTOR GUIDE</span><h1>Contribute to OpenRoadmap.</h1><p>Create learning paths, improve the standard, and help people know what to learn and where to look.</p><div className="heroactions"><a className="primary" href="#public">Contribute a roadmap</a><a className="secondary" href="https://github.com/dathrob/openroadmap" target="_blank" rel="noreferrer">Improve OpenRoadmap ↗</a></div><p className="guide-note">Everyone can contribute. No OpenRoadmap account is required. GitHub is the contribution platform.</p></section><section className="governance-callout"><strong>Protected main</strong><span>No direct pushes.</span><b>Branch → Pull Request → CI → Review → Merge</b></section><section className="guide-section" id="paths"><span className="kicker">WHO CAN CONTRIBUTE?</span><h2>Two paths. One review standard.</h2><div className="path-grid"><Path title="Public Contributor" note="For anyone contributing a roadmap. No repository access required." steps={publicSteps} cta="Contribute a roadmap" href="#public"/><Path title="Repository Contributor" note="For trusted contributors with canonical repository access." steps={repoSteps} cta="Read contribution rules" href="#repository" extra="Repository access does not permit direct pushes to main."/></div></section><section className="guide-section" id="public"><span className="kicker">PUBLIC ROADMAP WORKFLOW</span><h2>Create your first roadmap.</h2><div className="workflow-list">{['Fork OpenRoadmap','Clone your fork','Create roadmap/<slug>','Build your roadmap','Validate locally','Commit your branch','Push to your fork','Open a Pull Request'].map((x,i)=><div key={x}><b>{String(i+1).padStart(2,'0')}</b><span>{x}</span></div>)}</div><pre>{`git clone https://github.com/YOUR_USERNAME/openroadmap.git
cd openroadmap
git checkout -b roadmap/my-roadmap
npm install
npm run validate
git add .
git commit -m "roadmap: add my roadmap"
git push -u origin roadmap/my-roadmap`}</pre></section><section className="guide-section" id="repository"><span className="kicker">REPOSITORY CONTRIBUTORS</span><h2>Trusted access, same PR policy.</h2><p>Repository Contributors may work on code, UI, docs, tests, tooling, roadmaps, and fixes. Create a branch in <code>dathrob/openroadmap</code>, validate it, push the branch, and open a PR into <code>main</code>. The maintainer reviews and merges; contributors do not bypass the pull request workflow.</p></section><section className="guide-section"><span className="kicker">BUILD IT YOUR WAY</span><h2>Human, AI, or Hybrid.</h2><div className="provenance-grid"><div><b>HUMAN</b><p>Written and curated primarily by a person.</p></div><div><b>AI</b><p>Generated primarily with a disclosed AI system.</p></div><div><b>HYBRID</b><p>Created through meaningful human and AI collaboration.</p></div></div><p>Authorship describes how a roadmap was created; it is not a quality score. AI and Hybrid contributions must disclose truthful provenance. <Link href="/docs/ai-authoring">AI authoring</Link> · <Link href="/docs/specification">Specification</Link></p><pre>{`Authorship: AI
Provider: OpenAI
Model: example-model
Generated: YYYY-MM-DD`}</pre></section><section className="guide-section"><span className="kicker">ACCEPTED ≠ VERIFIED</span><h2>Published is not Verified.</h2><div className="status-flow"><div><b>ACCEPTED</b><span>PR reviewed and merged → Published</span></div><div><b>VERIFIED</b><span>Separate verification process → Badge</span></div></div><p>Verification means a roadmap meets OpenRoadmap’s defined verification requirements. It does not mean best, official, guaranteed, or highest quality.</p></section><section className="guide-section"><span className="kicker">REVIEW PIPELINE</span><h2>Transparent by design.</h2><div className="pipeline">{['Submission','Schema validation','Tests','Maintainer review','Changes requested or accepted','Merge','Published'].map((x,i)=><span key={x}>{String(i+1).padStart(2,'0')} {x}</span>)}</div></section><section className="guide-section"><span className="kicker">GENERATE WITH YOUR LLM</span><h2>Use the agent you already have.</h2><p>OpenRoadmap does not provide an AI generator. Your coding agent reads the repository instructions, creates the YAML, discloses provenance, and validates it.</p><pre>{prompt}</pre><button className="primary copybtn" onClick={copy}>{copied?'Copied':'Copy canonical prompt'}</button></section></main>}
function Path({title,note,steps,cta,href,extra}:{title:string;note:string;steps:string[];cta:string;href:string;extra?:string}){return <article className="path-card"><span className="kicker">{title.toUpperCase()}</span><h3>{title}</h3><p>{note}</p><div className="path-steps">{steps.map((x,i)=><span key={x}><b>{String(i+1).padStart(2,'0')}</b>{x}</span>)}</div>{extra&&<small>{extra}</small>}<a className="secondary" href={href}>{cta} →</a></article>}
